function  CreateFigure_Obj(Px,Py,Pz,sumImg,Iteracion,Bw)
%UNTITLED Summary of this function goes here

figure();

 surf( Px(1:2:end, 1:10:end), ...
      Py(1:2:end, 1:10:end), ...
      Pz(1:2:end, 1:10:end), ...
      'EdgeColor','None', ...
      'CData',sumImg(1:2:end, 1:10:end,:) );

  % surf( Px(1:2:end, 1:10:end), ...
  %     Py(1:2:end, 1:10:end), ...
  %     Pz(1:2:end, 1:10:end), ...
  %     'EdgeColor','None' );
      light
      daspect([1,1,1]);title(strcat( 'ite .',num2str(Iteracion) ,' Reconstruccion Objeto')); 


end